### ISSUE TITLE
A_prefix bug

### ISSUE THREAD

**Issue by Konstancja** [astroolka/cta-neutrino#17]
A_prefix badly defined in: nu_trans_detect.py and nu_trans_detect_stable.py
`A_prefix = np.pow(2.,-gam-1)`
should be:
`A_prefix = np.power(2.,-gam-1)`
Sam eproblem for pp and pph options.

**Comment by astroolka** [comment]
Now should be fixed.

**Comment by astroolka** [comment]
Thanks!
